import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDev = process.env.NODE_ENV === "development";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isDev && (
          <a
            href="http://localhost:3333"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed top-3 right-3 z-50 px-3 py-1.5 text-sm font-medium bg-orange-500 text-white rounded shadow hover:bg-orange-600"
          >
            Sanity Studio →
          </a>
        )}
        {children}
      </body>
    </html>
  );
}
