import {defineField, defineType} from 'sanity'

export const homepage = defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  fields: [
    defineField({
      name: 'heroArticle',
      title: 'Hero Article',
      type: 'reference',
      to: [{type: 'article'}],
      description: 'Primary hero article on the homepage.',
    }),
    defineField({
      name: 'heroLayout',
      title: 'Hero Layout',
      type: 'string',
      options: {
        list: [
          {title: 'Split – White (image right, text left)', value: 'split-white'},
          {title: 'Split – Dark (image left, text right on black)', value: 'split-dark'},
          {title: 'Full Bleed (image with text overlay)', value: 'full-bleed'},
        ],
        layout: 'radio',
      },
      initialValue: 'split-white',
      description: 'Layout style for the hero feature block.',
    }),
    defineField({
      name: 'heroTextPosition',
      title: 'Hero Text Position',
      type: 'string',
      options: {
        list: [
          {title: 'Bottom Left', value: 'bottom-left'},
          {title: 'Bottom Center', value: 'bottom-center'},
          {title: 'Bottom Right', value: 'bottom-right'},
          {title: 'Center', value: 'center'},
          {title: 'Top Left', value: 'top-left'},
          {title: 'Top Center', value: 'top-center'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'bottom-left',
      description: 'Where to place the text on a Full Bleed layout. Ignored for split layouts.',
    }),
    defineField({
      name: 'heroTextWidth',
      title: 'Hero Text Width',
      type: 'string',
      options: {
        list: [
          {title: 'Narrow (~600px)', value: 'narrow'},
          {title: 'Medium (~800px)', value: 'medium'},
          {title: 'Wide (~1000px)', value: 'wide'},
          {title: 'Full', value: 'full'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'How wide the text block spans on a Full Bleed layout. Ignored for split layouts.',
    }),
    defineField({
      name: 'heroHeadlineSize',
      title: 'Hero Headline Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
          {title: 'Extra Large', value: 'xl'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Headline font size for the hero Full Bleed layout.',
    }),
    defineField({
      name: 'heroBodySize',
      title: 'Hero Body Text Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Body text size for the hero Full Bleed layout.',
    }),
    defineField({
      name: 'heroTextColor',
      title: 'Hero Text Color',
      type: 'color',
      description: 'Text color for the hero Full Bleed layout. Defaults to white if not set.',
    }),
    defineField({
      name: 'secondaryFeature',
      title: 'Secondary Feature',
      type: 'reference',
      to: [{type: 'article'}],
      description: 'Secondary feature article block.',
    }),
    defineField({
      name: 'secondaryLayout',
      title: 'Secondary Feature Layout',
      type: 'string',
      options: {
        list: [
          {title: 'Split – White (image right, text left)', value: 'split-white'},
          {title: 'Split – Dark (image left, text right on black)', value: 'split-dark'},
          {title: 'Full Bleed (image with text overlay)', value: 'full-bleed'},
        ],
        layout: 'radio',
      },
      initialValue: 'split-dark',
      description: 'Layout style for the secondary feature block.',
    }),
    defineField({
      name: 'secondaryTextPosition',
      title: 'Secondary Text Position',
      type: 'string',
      options: {
        list: [
          {title: 'Bottom Left', value: 'bottom-left'},
          {title: 'Bottom Center', value: 'bottom-center'},
          {title: 'Bottom Right', value: 'bottom-right'},
          {title: 'Center', value: 'center'},
          {title: 'Top Left', value: 'top-left'},
          {title: 'Top Center', value: 'top-center'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'bottom-left',
      description: 'Where to place the text on a Full Bleed layout. Ignored for split layouts.',
    }),
    defineField({
      name: 'secondaryTextWidth',
      title: 'Secondary Text Width',
      type: 'string',
      options: {
        list: [
          {title: 'Narrow (~600px)', value: 'narrow'},
          {title: 'Medium (~800px)', value: 'medium'},
          {title: 'Wide (~1000px)', value: 'wide'},
          {title: 'Full', value: 'full'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'How wide the text block spans on a Full Bleed layout. Ignored for split layouts.',
    }),
    defineField({
      name: 'secondaryHeadlineSize',
      title: 'Secondary Headline Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
          {title: 'Extra Large', value: 'xl'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Headline font size for the secondary Full Bleed layout.',
    }),
    defineField({
      name: 'secondaryBodySize',
      title: 'Secondary Body Text Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Body text size for the secondary Full Bleed layout.',
    }),
    defineField({
      name: 'secondaryTextColor',
      title: 'Secondary Text Color',
      type: 'color',
      description: 'Text color for the secondary Full Bleed layout. Defaults to white if not set.',
    }),
    defineField({
      name: 'gridOne',
      title: 'Grid One',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'article'}]}],
      validation: (Rule) => Rule.max(4),
      description: 'First homepage article grid (max 4).',
    }),
    defineField({
      name: 'gridTwo',
      title: 'Grid Two',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'article'}]}],
      validation: (Rule) => Rule.max(4),
      description: 'Second homepage article grid (max 4).',
    }),
    defineField({
      name: 'issueHighlight',
      title: 'Issue Highlight',
      type: 'reference',
      to: [{type: 'article'}],
      description: 'Optional highlighted article block.',
    }),
    defineField({
      name: 'announcementMessage',
      title: 'Announcement Message',
      type: 'string',
      description: 'Main sentence shown in the homepage announcement bar.',
      validation: (Rule) => Rule.required().max(180),
    }),
    defineField({
      name: 'announcementLinkLabel',
      title: 'Announcement Link Label',
      type: 'string',
      description: 'Clickable link text in the homepage announcement bar.',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'announcementLinkUrl',
      title: 'Announcement Link URL',
      type: 'url',
      description: 'Destination URL for the homepage announcement link.',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    prepare: () => ({
      title: 'Homepage',
    }),
  },
})
