import {defineField, defineType} from 'sanity'

export const homepage = defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  fields: [
    defineField({
      name: 'heroArticle',
      title: 'Hero Article',
      type: 'reference',
      to: [{type: 'article'}, {type: 'projectProfile'}],
      description: 'Primary hero article or project profile on the homepage.',
    }),
    defineField({
      name: 'heroLayout',
      title: 'Hero Layout',
      type: 'string',
      options: {
        list: [
          {title: 'Split – White (image right, text left)', value: 'split-white'},
          {title: 'Split – Dark (image left, text right on black)', value: 'split-dark'},
          {title: 'Full Bleed (image with text overlay)', value: 'full-bleed'},
        ],
        layout: 'radio',
      },
      initialValue: 'split-white',
      description: 'Layout style for the hero feature block.',
    }),
    defineField({
      name: 'heroTextPosition',
      title: 'Hero Text Position',
      type: 'string',
      options: {
        list: [
          {title: 'Bottom Left', value: 'bottom-left'},
          {title: 'Bottom Center', value: 'bottom-center'},
          {title: 'Bottom Right', value: 'bottom-right'},
          {title: 'Center', value: 'center'},
          {title: 'Top Left', value: 'top-left'},
          {title: 'Top Center', value: 'top-center'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'bottom-left',
      description: 'Where to place the text on a Full Bleed layout.',
      hidden: ({parent}) => parent?.heroLayout !== 'full-bleed',
    }),
    defineField({
      name: 'heroTextWidth',
      title: 'Hero Text Width',
      type: 'string',
      options: {
        list: [
          {title: 'Narrow (~600px)', value: 'narrow'},
          {title: 'Medium (~800px)', value: 'medium'},
          {title: 'Wide (~1000px)', value: 'wide'},
          {title: 'Full', value: 'full'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'How wide the text block spans on a Full Bleed layout.',
      hidden: ({parent}) => parent?.heroLayout !== 'full-bleed',
    }),
    defineField({
      name: 'heroHeadlineSize',
      title: 'Hero Headline Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
          {title: 'Extra Large', value: 'xl'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Headline font size for the hero feature block.',
    }),
    defineField({
      name: 'heroBodySize',
      title: 'Hero Body Text Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Body text size for the hero feature block.',
    }),
    defineField({
      name: 'heroTextColor',
      title: 'Hero Text Color',
      type: 'color',
      description: 'Text color for the hero block. Defaults to white (full-bleed/dark) or black (white split).',
    }),
    defineField({
      name: 'heroSplitBgColor',
      title: 'Hero Split Background Color',
      type: 'color',
      description: 'Background color for the text block in split layouts. Defaults to white or black based on layout.',
      hidden: ({parent}) => parent?.heroLayout === 'full-bleed',
    }),
    defineField({
      name: 'heroSplitGradient',
      title: 'Hero Split Gradient',
      type: 'boolean',
      initialValue: false,
      description: 'Enable a gradient background on the split layout text block.',
      hidden: ({parent}) => parent?.heroLayout === 'full-bleed',
    }),
    defineField({
      name: 'heroSplitGradientDirection',
      title: 'Hero Gradient Direction',
      type: 'string',
      options: {
        list: [
          {title: 'Top to Bottom', value: 'to bottom'},
          {title: 'Bottom to Top', value: 'to top'},
          {title: 'Left to Right', value: 'to right'},
          {title: 'Right to Left', value: 'to left'},
          {title: 'Top-Left to Bottom-Right', value: 'to bottom right'},
          {title: 'Top-Right to Bottom-Left', value: 'to bottom left'},
          {title: 'Bottom-Left to Top-Right', value: 'to top right'},
          {title: 'Bottom-Right to Top-Left', value: 'to top left'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'to bottom',
      description: 'Direction of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.heroLayout === 'full-bleed' || !parent?.heroSplitGradient,
    }),
    defineField({
      name: 'heroSplitGradientFrom',
      title: 'Hero Gradient Start Color',
      type: 'color',
      description: 'Starting color of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.heroLayout === 'full-bleed' || !parent?.heroSplitGradient,
    }),
    defineField({
      name: 'heroSplitGradientTo',
      title: 'Hero Gradient End Color',
      type: 'color',
      description: 'Ending color of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.heroLayout === 'full-bleed' || !parent?.heroSplitGradient,
    }),
    defineField({
      name: 'secondaryFeature',
      title: 'Secondary Feature',
      type: 'reference',
      to: [{type: 'article'}, {type: 'projectProfile'}],
      description: 'Secondary feature article or project profile block.',
    }),
    defineField({
      name: 'secondaryLayout',
      title: 'Secondary Feature Layout',
      type: 'string',
      options: {
        list: [
          {title: 'Split – White (image right, text left)', value: 'split-white'},
          {title: 'Split – Dark (image left, text right on black)', value: 'split-dark'},
          {title: 'Full Bleed (image with text overlay)', value: 'full-bleed'},
        ],
        layout: 'radio',
      },
      initialValue: 'split-dark',
      description: 'Layout style for the secondary feature block.',
    }),
    defineField({
      name: 'secondaryTextPosition',
      title: 'Secondary Text Position',
      type: 'string',
      options: {
        list: [
          {title: 'Bottom Left', value: 'bottom-left'},
          {title: 'Bottom Center', value: 'bottom-center'},
          {title: 'Bottom Right', value: 'bottom-right'},
          {title: 'Center', value: 'center'},
          {title: 'Top Left', value: 'top-left'},
          {title: 'Top Center', value: 'top-center'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'bottom-left',
      description: 'Where to place the text on a Full Bleed layout.',
      hidden: ({parent}) => parent?.secondaryLayout !== 'full-bleed',
    }),
    defineField({
      name: 'secondaryTextWidth',
      title: 'Secondary Text Width',
      type: 'string',
      options: {
        list: [
          {title: 'Narrow (~600px)', value: 'narrow'},
          {title: 'Medium (~800px)', value: 'medium'},
          {title: 'Wide (~1000px)', value: 'wide'},
          {title: 'Full', value: 'full'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'How wide the text block spans on a Full Bleed layout.',
      hidden: ({parent}) => parent?.secondaryLayout !== 'full-bleed',
    }),
    defineField({
      name: 'secondaryHeadlineSize',
      title: 'Secondary Headline Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
          {title: 'Extra Large', value: 'xl'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Headline font size for the secondary feature block.',
    }),
    defineField({
      name: 'secondaryBodySize',
      title: 'Secondary Body Text Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Body text size for the secondary feature block.',
    }),
    defineField({
      name: 'secondaryTextColor',
      title: 'Secondary Text Color',
      type: 'color',
      description: 'Text color for the secondary block. Defaults to white (full-bleed/dark) or black (white split).',
    }),
    defineField({
      name: 'secondarySplitBgColor',
      title: 'Secondary Split Background Color',
      type: 'color',
      description: 'Background color for the text block in split layouts. Defaults to white or black based on layout.',
      hidden: ({parent}) => parent?.secondaryLayout === 'full-bleed',
    }),
    defineField({
      name: 'secondarySplitGradient',
      title: 'Secondary Split Gradient',
      type: 'boolean',
      initialValue: false,
      description: 'Enable a gradient background on the split layout text block.',
      hidden: ({parent}) => parent?.secondaryLayout === 'full-bleed',
    }),
    defineField({
      name: 'secondarySplitGradientDirection',
      title: 'Secondary Gradient Direction',
      type: 'string',
      options: {
        list: [
          {title: 'Top to Bottom', value: 'to bottom'},
          {title: 'Bottom to Top', value: 'to top'},
          {title: 'Left to Right', value: 'to right'},
          {title: 'Right to Left', value: 'to left'},
          {title: 'Top-Left to Bottom-Right', value: 'to bottom right'},
          {title: 'Top-Right to Bottom-Left', value: 'to bottom left'},
          {title: 'Bottom-Left to Top-Right', value: 'to top right'},
          {title: 'Bottom-Right to Top-Left', value: 'to top left'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'to bottom',
      description: 'Direction of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.secondaryLayout === 'full-bleed' || !parent?.secondarySplitGradient,
    }),
    defineField({
      name: 'secondarySplitGradientFrom',
      title: 'Secondary Gradient Start Color',
      type: 'color',
      description: 'Starting color of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.secondaryLayout === 'full-bleed' || !parent?.secondarySplitGradient,
    }),
    defineField({
      name: 'secondarySplitGradientTo',
      title: 'Secondary Gradient End Color',
      type: 'color',
      description: 'Ending color of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.secondaryLayout === 'full-bleed' || !parent?.secondarySplitGradient,
    }),
    defineField({
      name: 'gridOne',
      title: 'Grid One',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'article'}, {type: 'projectProfile'}]}],
      validation: (Rule) => Rule.max(4),
      description: 'First homepage grid (max 4). Articles or project profiles.',
    }),
    defineField({
      name: 'gridTwo',
      title: 'Grid Two',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'article'}, {type: 'projectProfile'}]}],
      validation: (Rule) => Rule.max(4),
      description: 'Second homepage grid (max 4). Articles or project profiles.',
    }),
    defineField({
      name: 'tertiaryFeature',
      title: 'Tertiary Feature',
      type: 'reference',
      to: [{type: 'article'}, {type: 'projectProfile'}],
      description: 'Third feature article or project profile block.',
    }),
    defineField({
      name: 'tertiaryLayout',
      title: 'Tertiary Feature Layout',
      type: 'string',
      options: {
        list: [
          {title: 'Split – White (image right, text left)', value: 'split-white'},
          {title: 'Split – Dark (image left, text right on black)', value: 'split-dark'},
          {title: 'Full Bleed (image with text overlay)', value: 'full-bleed'},
        ],
        layout: 'radio',
      },
      initialValue: 'split-white',
      description: 'Layout style for the tertiary feature block.',
    }),
    defineField({
      name: 'tertiaryTextPosition',
      title: 'Tertiary Text Position',
      type: 'string',
      options: {
        list: [
          {title: 'Bottom Left', value: 'bottom-left'},
          {title: 'Bottom Center', value: 'bottom-center'},
          {title: 'Bottom Right', value: 'bottom-right'},
          {title: 'Center', value: 'center'},
          {title: 'Top Left', value: 'top-left'},
          {title: 'Top Center', value: 'top-center'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'bottom-left',
      description: 'Where to place the text on a Full Bleed layout.',
      hidden: ({parent}) => parent?.tertiaryLayout !== 'full-bleed',
    }),
    defineField({
      name: 'tertiaryTextWidth',
      title: 'Tertiary Text Width',
      type: 'string',
      options: {
        list: [
          {title: 'Narrow (~600px)', value: 'narrow'},
          {title: 'Medium (~800px)', value: 'medium'},
          {title: 'Wide (~1000px)', value: 'wide'},
          {title: 'Full', value: 'full'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'How wide the text block spans on a Full Bleed layout.',
      hidden: ({parent}) => parent?.tertiaryLayout !== 'full-bleed',
    }),
    defineField({
      name: 'tertiaryHeadlineSize',
      title: 'Tertiary Headline Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
          {title: 'Extra Large', value: 'xl'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Headline font size for the tertiary feature block.',
    }),
    defineField({
      name: 'tertiaryBodySize',
      title: 'Tertiary Body Text Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'small'},
          {title: 'Medium', value: 'medium'},
          {title: 'Large', value: 'large'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'medium',
      description: 'Body text size for the tertiary feature block.',
    }),
    defineField({
      name: 'tertiaryTextColor',
      title: 'Tertiary Text Color',
      type: 'color',
      description: 'Text color for the tertiary block. Defaults to white (full-bleed/dark) or black (white split).',
    }),
    defineField({
      name: 'tertiarySplitBgColor',
      title: 'Tertiary Split Background Color',
      type: 'color',
      description: 'Background color for the text block in split layouts. Defaults to white or black based on layout.',
      hidden: ({parent}) => parent?.tertiaryLayout === 'full-bleed',
    }),
    defineField({
      name: 'tertiarySplitGradient',
      title: 'Tertiary Split Gradient',
      type: 'boolean',
      initialValue: false,
      description: 'Enable a gradient background on the split layout text block.',
      hidden: ({parent}) => parent?.tertiaryLayout === 'full-bleed',
    }),
    defineField({
      name: 'tertiarySplitGradientDirection',
      title: 'Tertiary Gradient Direction',
      type: 'string',
      options: {
        list: [
          {title: 'Top to Bottom', value: 'to bottom'},
          {title: 'Bottom to Top', value: 'to top'},
          {title: 'Left to Right', value: 'to right'},
          {title: 'Right to Left', value: 'to left'},
          {title: 'Top-Left to Bottom-Right', value: 'to bottom right'},
          {title: 'Top-Right to Bottom-Left', value: 'to bottom left'},
          {title: 'Bottom-Left to Top-Right', value: 'to top right'},
          {title: 'Bottom-Right to Top-Left', value: 'to top left'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'to bottom',
      description: 'Direction of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.tertiaryLayout === 'full-bleed' || !parent?.tertiarySplitGradient,
    }),
    defineField({
      name: 'tertiarySplitGradientFrom',
      title: 'Tertiary Gradient Start Color',
      type: 'color',
      description: 'Starting color of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.tertiaryLayout === 'full-bleed' || !parent?.tertiarySplitGradient,
    }),
    defineField({
      name: 'tertiarySplitGradientTo',
      title: 'Tertiary Gradient End Color',
      type: 'color',
      description: 'Ending color of the gradient. Only used when gradient is enabled.',
      hidden: ({parent}) => parent?.tertiaryLayout === 'full-bleed' || !parent?.tertiarySplitGradient,
    }),
    defineField({
      name: 'gridThree',
      title: 'Grid Three',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'article'}, {type: 'projectProfile'}]}],
      validation: (Rule) => Rule.max(4),
      description: 'Third homepage grid (max 4). Articles or project profiles.',
    }),
    defineField({
      name: 'issueHighlight',
      title: 'Issue Highlight',
      type: 'reference',
      to: [{type: 'article'}, {type: 'projectProfile'}],
      description: 'Optional highlighted article or project profile block.',
    }),
    defineField({
      name: 'announcementMessage',
      title: 'Announcement Message',
      type: 'string',
      description: 'Main sentence shown in the homepage announcement bar.',
      validation: (Rule) => Rule.required().max(180),
    }),
    defineField({
      name: 'announcementLinkLabel',
      title: 'Announcement Link Label',
      type: 'string',
      description: 'Clickable link text in the homepage announcement bar.',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'announcementLinkUrl',
      title: 'Announcement Link URL',
      type: 'url',
      description: 'Destination URL for the homepage announcement link.',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    prepare: () => ({
      title: 'Homepage',
    }),
  },
})
